services:
  api:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./app:/var/www/app
      - ./router.php:/var/www/router.php
    environment:
      APP_ENV: production
    restart: unless-stopped
